name = "workers-airtable-form"
type = "javascript"

account_id = "e92a4ecede2c0bcf2e17ab3a48f519c1"
workers_dev = true

[vars]
AIRTABLE_BASE_ID = "appqTu5uObO0ZC4cZ"
AIRTABLE_TABLE_NAME = "CheckLab"
FORM_URL = "https://workers-airtable-form.pages.dev"
